#!/usr/bin/env bash

source test_secrets.sh

if [ -z "$1" ]
then
    echo "running tests except 'skip'"   # tests flagged as skip are skipped by default
    py.test -v -x --capture=no
fi


if [ "$1" = "testnow" ]
then
    echo "Running 'testnow' only"
    py.test -v -x --capture=no -m testnow
fi


